### PR TITLE
Create courses

### LINKED ISSUE #7: As a user, I can view a course
- [x] create `show` action in courses controller
- [x] add `show` in routes
- [x] Add bootstrap styling

### LINKED ISSUE #14: As a user, I can create a course
- [x]   create the user model
- [x]   create the course model
- [x]   create the course routes
- [x]   create the course controller
- [x]   create the course migration
- [x]   create the course views
- [x]   add consistent Bootstrap styling throughout the application

### PR DESCRIPTION
**Pull request by clarkngo**
This PR implements the following functionality:

resolves #14
resolves #7

### CODE REVIEW

**Comment by clarkngo** [comment]
Do you mean to remove `category` in `courses` table and create a `model` `category`?

**Comment by conradwt** [comment]
One needs setup the proper associations for the `Course` and `Category` models.  The `courses` table should have a field called `category_id` instead of a `category`.  In general, your models should be structured as follows:

```ruby
class Course < ApplicationRecord
  belongs_to :category 
end

class Category < ApplicationRecord
  has_many :courses
end
```

**Comment by conradwt** [comment]
At this time, I'm seeing the following issue:

1. sign up
2. sign in
3. click `Suggest New Course` link

Expected:

new course form

Actual:

```text
ActionController::ParameterMissing in CoursesController#new
```

**Comment by clarkngo** [comment]
Commit `user can update a course` fixes issue -#11

**Comment by clarkngo** [comment]
Commit `destroy action` fixes issue -#10
I couldn't pass the test for `destroy`
Need help on FactoryBot

**Comment by conradwt** [comment]
I recommend creating a separate PRs for each of the following:

update 
destroy

The current PR took a bit long with 2 users stories and no code has been deployed to master which should be happening on a daily basis.  Thus, the new rule is one user story between per PR starting with the destroy and update user stories.

**Comment by conradwt** [comment]
Here's the results of the code:

checked = approved
unchecked = not approved

- [ ] `application_controller.rb` - Please refactor to use techniques discussed in prior homework(s).

- [ ] `courses_controller.rb` - Please remove `edit`, `update`, and `destroy` methods and any associated dependencies.  Furthermore, one shouldn't be using `find_by_*` methods in the current version of Rails.

- [x] `app/models/category.rb`

- [x] `app/models/course.rb`

- [ ] `app/views/courses/edit.html.erb` - This file shouldn't be a part of this branch.

- [x] `app/views/courses/index.html.erb`

- [x] `app/views/courses/new.html.erb`

- [x] `app/views/courses/show.html.erb`

- [ ] `app/views/devise/_error_messages.html.erb` - Missing Bootstrap CSS selectors.

- [x] `app/views/homes/index.html.erb`

- [ ] `config/routes.rb` - Needs refactoring.  Please review Rails guides on routing.

- [x] `db/migrate/20190130225315_rename_category_on_categories.rb`

- [x]  `db/schema.rb`

- [ ] `db/seeds.rb` - Please fix indentation because there's a space prior to some of the `Course.create` lines.

- [ ] `spec/controllers/courses_controller_spec.rb` - Please remove because one should be creating only `feature` (i.e. integration) and `model` specs.

- [ ] `spec/controllers/homes_controller_spec.rb` - Please remove because this file isn't necessary.
 

- [ ] `spec/models/category_spec.rb` - Please remove because there's nothing being tested here.

- [ ] `spec/models/course_spec.rb` - Please remove because there's nothing being tested here.

- [ ] `spec/models/user_spec.rb` - Please remove because there's nothing being tested here.

**Comment by conradwt** [comment]
> Commit `user can update a course` fixes issue -#11
> I couldn't pass the tests for `create`, `edit` and `update`.
> 
> ```
>   1) CoursesController courses#create action should successfully create a new course in our database
>      Failure/Error: expect(response).to redirect_to root_path
>      
>        Expected response to be a <3XX: redirect>, but was a <422: Unprocessable Entity>
>        Response body: 
>      # ./spec/controllers/courses_controller_spec.rb:55:in `block (3 levels) in <top (required)>'
> 
> 2) CoursesController courses#edit action shouldn't let a user who did not create the course edit a course
>      Failure/Error:
>        course = FactoryBot.create(
>          course: { 
>            category: 'Preparatory',
>            name: 'Introduction to Computer Science',
>            description: 'This course is an introduction to computer science.'
>          } 
>        )
>      
>      ArgumentError:
>        Factory not registered: {:course=>{:category=>"Preparatory", :name=>"Introduction to Computer Science", :description=>"This course is an introduction to computer science."}}
> 
>  3) CoursesController courses#edit action shouldn't let unauthenticated users edit a course
>      Failure/Error: course = FactoryBot.create(:course)
>      
>      ActiveRecord::RecordInvalid:
>        Validation failed: Category can't be blank, Name can't be blank, Description can't be blank, User can't be blank, User must exist, Category must exist
> 
> ....
> ```

Please see review for further details.

**Pull request merged**
