### PR TITLE
User upload profile picture during sign up

### LINKED ISSUE #51: As a user, I can upload my profile picture.
- [x] install and configure the CarrierWave and AWS gems
- [x] setup AWS S3 associated bucket
- [x] upload picture during `sign up` process
- [x] upload picture after `sign in` process
- [x] when logged in, a circular profile picture should be displayed in the navbar
- [x] when a user creates a course, the creator information should include circular profile photo on the course's show page

### PR DESCRIPTION
**Pull request by clarkngo**
This PR implements the following functionality:

resolves #51

### CODE REVIEW

**Comment by conradwt** [comment]
This PR is missing the required files for the application to run.  For example, I'm getting the following error when setting up the DB:

```text
ArgumentError: Missing required arguments: aws_access_key_id, aws_secret_access_key
```

**Comment by clarkngo** [comment]
Add file `config/application.yml.example` for instructions to configure AWS Access Key, AWS Secret Key and AWS S3 Bucket for file storage use.

**Comment by clarkngo** [comment]
Steps taken:
1) Deleted `credentials.yml.enc` and `master.key`
2) Run `rails credentials:edit`
3) Stored AWS Access Key, AWS Secret Key, and AWS Bucket into `credentials.yml.enc`
4) Check Slack for updated `master.key`

**Comment by conradwt** [comment]
The following issuees prevented this PR from being approved:

- missing `master.key.example` file
- missing `master.key` setup instructions within `README.md`
- missing `application.yml` setup instructions within `README.md`
- AWS credentials not properly set within `credentials.yml.enc` file
- AWS credentials not properly set within `application.yml.example` file
   Note:  The sensitive credentials will be encrypted like AWS and Rails secret key base.
- feature `spec/features/user_upload_pic_at_sign_up.rb` not being ran by RSpec
   Note:  `rspec spec/features/user_upload_pic_at_sign_up.rb` fails.  Thus, you may want to verify your
               overall setup.
- rename `spec/features/user_upload_pic_at_sign_up.rb` to `spec/features/user_uploads_avatar_spec.rb`
- missing scenario within `spec/features/user_uploads_avatar_spec.rb` to test uploading a `avatar` after 
  a user `sign in` to their account

When the above issues have been resolved, please submit a new PR for review.  If you have any other question(s), please do let me know at your earliest.

**Comment by clarkngo** [comment]
* AWS credentials not properly set within `application.yml.example` file
  Note:  The sensitive credentials will be encrypted like AWS and Rails secret key base.
- does this mean i should create an `application.yml.enc` instead?

**Comment by conradwt** [comment]
@clarkngo You need to know how to access the variables within an `application.yml`.  Please review the Rails security guides for how to access variables from an encrypted file.

**Pull request closed without merging**
